// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module genChain_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        control_bits_V_119,
        p_in_0_sample_M_real_V_read,
        p_in_1_sample_M_real_V_read,
        p_in_2_sample_M_real_V_read,
        p_in_3_sample_M_real_V_read,
        p_in_4_sample_M_real_V_read,
        p_in_5_sample_M_real_V_read,
        p_in_6_sample_M_real_V_read,
        p_in_7_sample_M_real_V_read,
        p_in_8_sample_M_real_V_read,
        p_in_9_sample_M_real_V_read,
        p_in_10_sample_M_real_V_read,
        p_in_11_sample_M_real_V_read,
        p_in_12_sample_M_real_V_read,
        p_in_13_sample_M_real_V_read,
        p_in_14_sample_M_real_V_read,
        p_in_15_sample_M_real_V_read,
        p_in_0_sample_M_imag_V_read,
        p_in_1_sample_M_imag_V_read,
        p_in_2_sample_M_imag_V_read,
        p_in_3_sample_M_imag_V_read,
        p_in_4_sample_M_imag_V_read,
        p_in_5_sample_M_imag_V_read,
        p_in_6_sample_M_imag_V_read,
        p_in_7_sample_M_imag_V_read,
        p_in_8_sample_M_imag_V_read,
        p_in_9_sample_M_imag_V_read,
        p_in_10_sample_M_imag_V_read,
        p_in_11_sample_M_imag_V_read,
        p_in_12_sample_M_imag_V_read,
        p_in_13_sample_M_imag_V_read,
        p_in_14_sample_M_imag_V_read,
        p_in_15_sample_M_imag_V_read,
        p_in_0_valid_read,
        p_in_1_valid_read,
        p_in_2_valid_read,
        p_in_3_valid_read,
        p_in_4_valid_read,
        p_in_5_valid_read,
        p_in_6_valid_read,
        p_in_7_valid_read,
        p_in_8_valid_read,
        p_in_9_valid_read,
        p_in_10_valid_read,
        p_in_11_valid_read,
        p_in_12_valid_read,
        p_in_13_valid_read,
        p_in_14_valid_read,
        p_in_15_valid_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [3:0] control_bits_V_119;
input  [15:0] p_in_0_sample_M_real_V_read;
input  [15:0] p_in_1_sample_M_real_V_read;
input  [15:0] p_in_2_sample_M_real_V_read;
input  [15:0] p_in_3_sample_M_real_V_read;
input  [15:0] p_in_4_sample_M_real_V_read;
input  [15:0] p_in_5_sample_M_real_V_read;
input  [15:0] p_in_6_sample_M_real_V_read;
input  [15:0] p_in_7_sample_M_real_V_read;
input  [15:0] p_in_8_sample_M_real_V_read;
input  [15:0] p_in_9_sample_M_real_V_read;
input  [15:0] p_in_10_sample_M_real_V_read;
input  [15:0] p_in_11_sample_M_real_V_read;
input  [15:0] p_in_12_sample_M_real_V_read;
input  [15:0] p_in_13_sample_M_real_V_read;
input  [15:0] p_in_14_sample_M_real_V_read;
input  [15:0] p_in_15_sample_M_real_V_read;
input  [15:0] p_in_0_sample_M_imag_V_read;
input  [15:0] p_in_1_sample_M_imag_V_read;
input  [15:0] p_in_2_sample_M_imag_V_read;
input  [15:0] p_in_3_sample_M_imag_V_read;
input  [15:0] p_in_4_sample_M_imag_V_read;
input  [15:0] p_in_5_sample_M_imag_V_read;
input  [15:0] p_in_6_sample_M_imag_V_read;
input  [15:0] p_in_7_sample_M_imag_V_read;
input  [15:0] p_in_8_sample_M_imag_V_read;
input  [15:0] p_in_9_sample_M_imag_V_read;
input  [15:0] p_in_10_sample_M_imag_V_read;
input  [15:0] p_in_11_sample_M_imag_V_read;
input  [15:0] p_in_12_sample_M_imag_V_read;
input  [15:0] p_in_13_sample_M_imag_V_read;
input  [15:0] p_in_14_sample_M_imag_V_read;
input  [15:0] p_in_15_sample_M_imag_V_read;
input   p_in_0_valid_read;
input   p_in_1_valid_read;
input   p_in_2_valid_read;
input   p_in_3_valid_read;
input   p_in_4_valid_read;
input   p_in_5_valid_read;
input   p_in_6_valid_read;
input   p_in_7_valid_read;
input   p_in_8_valid_read;
input   p_in_9_valid_read;
input   p_in_10_valid_read;
input   p_in_11_valid_read;
input   p_in_12_valid_read;
input   p_in_13_valid_read;
input   p_in_14_valid_read;
input   p_in_15_valid_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [0:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [0:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [0:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [0:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [0:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [0:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [0:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [0:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [0:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [0:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;
output  [0:0] ap_return_32;
output  [15:0] ap_return_33;
output  [15:0] ap_return_34;
output  [0:0] ap_return_35;
output  [15:0] ap_return_36;
output  [15:0] ap_return_37;
output  [0:0] ap_return_38;
output  [15:0] ap_return_39;
output  [15:0] ap_return_40;
output  [0:0] ap_return_41;
output  [15:0] ap_return_42;
output  [15:0] ap_return_43;
output  [0:0] ap_return_44;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_11001;
reg    control_delayline_Ar_9_ce0;
reg    control_delayline_Ar_9_we0;
wire   [31:0] control_delayline_Ar_9_q0;
reg    control_delayline_Ar_57_ce0;
reg    control_delayline_Ar_57_we0;
wire   [31:0] control_delayline_Ar_57_q0;
reg    control_delayline_Ar_59_ce0;
reg    control_delayline_Ar_59_we0;
wire   [31:0] control_delayline_Ar_59_q0;
reg    control_delayline_Ar_60_ce0;
reg    control_delayline_Ar_60_we0;
wire   [31:0] control_delayline_Ar_60_q0;
reg   [0:0] p_in_15_valid_read9_reg_1232;
reg   [0:0] p_in_15_valid_read9_reg_1232_pp0_iter1_reg;
reg   [0:0] p_in_14_valid_read9_reg_1241;
reg   [0:0] p_in_14_valid_read9_reg_1241_pp0_iter1_reg;
reg   [0:0] p_in_13_valid_read9_reg_1250;
reg   [0:0] p_in_13_valid_read9_reg_1250_pp0_iter1_reg;
reg   [0:0] p_in_12_valid_read9_reg_1259;
reg   [0:0] p_in_12_valid_read9_reg_1259_pp0_iter1_reg;
reg   [0:0] p_in_11_valid_read9_reg_1268;
reg   [0:0] p_in_11_valid_read9_reg_1268_pp0_iter1_reg;
reg   [0:0] p_in_10_valid_read_6_reg_1277;
reg   [0:0] p_in_10_valid_read_6_reg_1277_pp0_iter1_reg;
reg   [0:0] p_in_9_valid_read_6_reg_1286;
reg   [0:0] p_in_9_valid_read_6_reg_1286_pp0_iter1_reg;
reg   [0:0] p_in_8_valid_read_6_reg_1295;
reg   [0:0] p_in_8_valid_read_6_reg_1295_pp0_iter1_reg;
reg   [0:0] p_in_7_valid_read_6_reg_1304;
reg   [0:0] p_in_7_valid_read_6_reg_1304_pp0_iter1_reg;
reg   [0:0] p_in_6_valid_read_6_reg_1313;
reg   [0:0] p_in_6_valid_read_6_reg_1313_pp0_iter1_reg;
reg   [0:0] p_in_5_valid_read85_reg_1322;
reg   [0:0] p_in_5_valid_read85_reg_1322_pp0_iter1_reg;
reg   [0:0] p_in_4_valid_read84_reg_1331;
reg   [0:0] p_in_4_valid_read84_reg_1331_pp0_iter1_reg;
reg   [0:0] p_in_3_valid_read83_reg_1340;
reg   [0:0] p_in_3_valid_read83_reg_1340_pp0_iter1_reg;
reg   [0:0] p_in_2_valid_read82_reg_1349;
reg   [0:0] p_in_2_valid_read82_reg_1349_pp0_iter1_reg;
reg   [0:0] p_in_1_valid_read81_reg_1358;
reg   [0:0] p_in_1_valid_read81_reg_1358_pp0_iter1_reg;
reg   [0:0] p_in_0_valid_read_14_reg_1367;
reg   [0:0] p_in_0_valid_read_14_reg_1367_pp0_iter1_reg;
reg   [15:0] p_in_15_sample_M_i_reg_1376;
reg   [15:0] p_in_15_sample_M_i_reg_1376_pp0_iter1_reg;
reg   [15:0] p_in_14_sample_M_i_reg_1385;
reg   [15:0] p_in_14_sample_M_i_reg_1385_pp0_iter1_reg;
reg   [15:0] p_in_13_sample_M_i_reg_1394;
reg   [15:0] p_in_13_sample_M_i_reg_1394_pp0_iter1_reg;
reg   [15:0] p_in_12_sample_M_i_reg_1403;
reg   [15:0] p_in_12_sample_M_i_reg_1403_pp0_iter1_reg;
reg   [15:0] p_in_11_sample_M_i_reg_1412;
reg   [15:0] p_in_11_sample_M_i_reg_1412_pp0_iter1_reg;
reg   [15:0] p_in_10_sample_M_i_reg_1421;
reg   [15:0] p_in_10_sample_M_i_reg_1421_pp0_iter1_reg;
reg   [15:0] p_in_9_sample_M_im_reg_1430;
reg   [15:0] p_in_9_sample_M_im_reg_1430_pp0_iter1_reg;
reg   [15:0] p_in_8_sample_M_im_reg_1439;
reg   [15:0] p_in_8_sample_M_im_reg_1439_pp0_iter1_reg;
reg   [15:0] p_in_7_sample_M_im_reg_1448;
reg   [15:0] p_in_7_sample_M_im_reg_1448_pp0_iter1_reg;
reg   [15:0] p_in_6_sample_M_im_reg_1457;
reg   [15:0] p_in_6_sample_M_im_reg_1457_pp0_iter1_reg;
reg   [15:0] p_in_5_sample_M_im_reg_1466;
reg   [15:0] p_in_5_sample_M_im_reg_1466_pp0_iter1_reg;
reg   [15:0] p_in_4_sample_M_im_reg_1475;
reg   [15:0] p_in_4_sample_M_im_reg_1475_pp0_iter1_reg;
reg   [15:0] p_in_3_sample_M_im_reg_1484;
reg   [15:0] p_in_3_sample_M_im_reg_1484_pp0_iter1_reg;
reg   [15:0] p_in_2_sample_M_im_reg_1493;
reg   [15:0] p_in_2_sample_M_im_reg_1493_pp0_iter1_reg;
reg   [15:0] p_in_1_sample_M_im_reg_1502;
reg   [15:0] p_in_1_sample_M_im_reg_1502_pp0_iter1_reg;
reg   [15:0] p_in_0_sample_M_im_reg_1511;
reg   [15:0] p_in_0_sample_M_im_reg_1511_pp0_iter1_reg;
reg   [15:0] p_in_15_sample_M_r_reg_1520;
reg   [15:0] p_in_15_sample_M_r_reg_1520_pp0_iter1_reg;
reg   [15:0] p_in_14_sample_M_r_reg_1529;
reg   [15:0] p_in_14_sample_M_r_reg_1529_pp0_iter1_reg;
reg   [15:0] p_in_13_sample_M_r_reg_1538;
reg   [15:0] p_in_13_sample_M_r_reg_1538_pp0_iter1_reg;
reg   [15:0] p_in_12_sample_M_r_reg_1547;
reg   [15:0] p_in_12_sample_M_r_reg_1547_pp0_iter1_reg;
reg   [15:0] p_in_11_sample_M_r_reg_1556;
reg   [15:0] p_in_11_sample_M_r_reg_1556_pp0_iter1_reg;
reg   [15:0] p_in_10_sample_M_r_reg_1565;
reg   [15:0] p_in_10_sample_M_r_reg_1565_pp0_iter1_reg;
reg   [15:0] p_in_9_sample_M_re_reg_1574;
reg   [15:0] p_in_9_sample_M_re_reg_1574_pp0_iter1_reg;
reg   [15:0] p_in_8_sample_M_re_reg_1583;
reg   [15:0] p_in_8_sample_M_re_reg_1583_pp0_iter1_reg;
reg   [15:0] p_in_7_sample_M_re_reg_1592;
reg   [15:0] p_in_7_sample_M_re_reg_1592_pp0_iter1_reg;
reg   [15:0] p_in_6_sample_M_re_reg_1601;
reg   [15:0] p_in_6_sample_M_re_reg_1601_pp0_iter1_reg;
reg   [15:0] p_in_5_sample_M_re_reg_1610;
reg   [15:0] p_in_5_sample_M_re_reg_1610_pp0_iter1_reg;
reg   [15:0] p_in_4_sample_M_re_reg_1619;
reg   [15:0] p_in_4_sample_M_re_reg_1619_pp0_iter1_reg;
reg   [15:0] p_in_3_sample_M_re_reg_1628;
reg   [15:0] p_in_3_sample_M_re_reg_1628_pp0_iter1_reg;
reg   [15:0] p_in_2_sample_M_re_reg_1637;
reg   [15:0] p_in_2_sample_M_re_reg_1637_pp0_iter1_reg;
reg   [15:0] p_in_1_sample_M_re_reg_1646;
reg   [15:0] p_in_1_sample_M_re_reg_1646_pp0_iter1_reg;
reg   [15:0] p_in_0_sample_M_re_reg_1655;
reg   [15:0] p_in_0_sample_M_re_reg_1655_pp0_iter1_reg;
reg   [3:0] control_bits_V_119_r_reg_1664;
reg   [3:0] control_bits_V_119_r_reg_1664_pp0_iter1_reg;
wire   [3:0] trunc_ln302_fu_533_p1;
reg   [3:0] trunc_ln302_reg_1671;
reg   [3:0] trunc_ln302_reg_1671_pp0_iter1_reg;
wire   [3:0] trunc_ln302_10_fu_550_p1;
reg   [3:0] trunc_ln302_10_reg_1679;
wire   [3:0] trunc_ln302_11_fu_568_p1;
reg   [3:0] trunc_ln302_11_reg_1686;
wire   [15:0] p_out_1_sample_M_r_fu_572_p18;
reg   [15:0] p_out_1_sample_M_r_reg_1694;
reg   [15:0] p_out_1_sample_M_r_reg_1694_pp0_iter3_reg;
reg   [15:0] p_out_1_sample_M_r_reg_1694_pp0_iter4_reg;
reg   [15:0] p_out_1_sample_M_r_reg_1694_pp0_iter5_reg;
reg   [15:0] p_out_1_sample_M_r_reg_1694_pp0_iter6_reg;
wire   [15:0] p_out_1_sample_M_i_fu_593_p18;
reg   [15:0] p_out_1_sample_M_i_reg_1699;
reg   [15:0] p_out_1_sample_M_i_reg_1699_pp0_iter3_reg;
reg   [15:0] p_out_1_sample_M_i_reg_1699_pp0_iter4_reg;
reg   [15:0] p_out_1_sample_M_i_reg_1699_pp0_iter5_reg;
reg   [15:0] p_out_1_sample_M_i_reg_1699_pp0_iter6_reg;
wire   [0:0] p_out_1_valid_write_fu_614_p18;
reg   [0:0] p_out_1_valid_write_reg_1704;
reg   [0:0] p_out_1_valid_write_reg_1704_pp0_iter3_reg;
reg   [0:0] p_out_1_valid_write_reg_1704_pp0_iter4_reg;
reg   [0:0] p_out_1_valid_write_reg_1704_pp0_iter5_reg;
reg   [0:0] p_out_1_valid_write_reg_1704_pp0_iter6_reg;
wire   [15:0] p_out_2_sample_M_r_fu_635_p18;
reg   [15:0] p_out_2_sample_M_r_reg_1709;
reg   [15:0] p_out_2_sample_M_r_reg_1709_pp0_iter3_reg;
reg   [15:0] p_out_2_sample_M_r_reg_1709_pp0_iter4_reg;
reg   [15:0] p_out_2_sample_M_r_reg_1709_pp0_iter5_reg;
reg   [15:0] p_out_2_sample_M_r_reg_1709_pp0_iter6_reg;
wire   [15:0] p_out_2_sample_M_i_fu_656_p18;
reg   [15:0] p_out_2_sample_M_i_reg_1714;
reg   [15:0] p_out_2_sample_M_i_reg_1714_pp0_iter3_reg;
reg   [15:0] p_out_2_sample_M_i_reg_1714_pp0_iter4_reg;
reg   [15:0] p_out_2_sample_M_i_reg_1714_pp0_iter5_reg;
reg   [15:0] p_out_2_sample_M_i_reg_1714_pp0_iter6_reg;
wire   [0:0] p_out_2_valid_write_fu_677_p18;
reg   [0:0] p_out_2_valid_write_reg_1719;
reg   [0:0] p_out_2_valid_write_reg_1719_pp0_iter3_reg;
reg   [0:0] p_out_2_valid_write_reg_1719_pp0_iter4_reg;
reg   [0:0] p_out_2_valid_write_reg_1719_pp0_iter5_reg;
reg   [0:0] p_out_2_valid_write_reg_1719_pp0_iter6_reg;
wire   [15:0] p_out_3_sample_M_r_fu_698_p18;
reg   [15:0] p_out_3_sample_M_r_reg_1724;
reg   [15:0] p_out_3_sample_M_r_reg_1724_pp0_iter3_reg;
reg   [15:0] p_out_3_sample_M_r_reg_1724_pp0_iter4_reg;
reg   [15:0] p_out_3_sample_M_r_reg_1724_pp0_iter5_reg;
reg   [15:0] p_out_3_sample_M_r_reg_1724_pp0_iter6_reg;
wire   [15:0] p_out_3_sample_M_i_fu_719_p18;
reg   [15:0] p_out_3_sample_M_i_reg_1729;
reg   [15:0] p_out_3_sample_M_i_reg_1729_pp0_iter3_reg;
reg   [15:0] p_out_3_sample_M_i_reg_1729_pp0_iter4_reg;
reg   [15:0] p_out_3_sample_M_i_reg_1729_pp0_iter5_reg;
reg   [15:0] p_out_3_sample_M_i_reg_1729_pp0_iter6_reg;
wire   [0:0] p_out_3_valid_write_fu_740_p18;
reg   [0:0] p_out_3_valid_write_reg_1734;
reg   [0:0] p_out_3_valid_write_reg_1734_pp0_iter3_reg;
reg   [0:0] p_out_3_valid_write_reg_1734_pp0_iter4_reg;
reg   [0:0] p_out_3_valid_write_reg_1734_pp0_iter5_reg;
reg   [0:0] p_out_3_valid_write_reg_1734_pp0_iter6_reg;
wire   [15:0] p_out_4_sample_M_r_fu_774_p18;
reg   [15:0] p_out_4_sample_M_r_reg_1739;
reg   [15:0] p_out_4_sample_M_r_reg_1739_pp0_iter3_reg;
reg   [15:0] p_out_4_sample_M_r_reg_1739_pp0_iter4_reg;
reg   [15:0] p_out_4_sample_M_r_reg_1739_pp0_iter5_reg;
reg   [15:0] p_out_4_sample_M_r_reg_1739_pp0_iter6_reg;
wire   [15:0] p_out_4_sample_M_i_fu_795_p18;
reg   [15:0] p_out_4_sample_M_i_reg_1744;
reg   [15:0] p_out_4_sample_M_i_reg_1744_pp0_iter3_reg;
reg   [15:0] p_out_4_sample_M_i_reg_1744_pp0_iter4_reg;
reg   [15:0] p_out_4_sample_M_i_reg_1744_pp0_iter5_reg;
reg   [15:0] p_out_4_sample_M_i_reg_1744_pp0_iter6_reg;
wire   [0:0] p_out_4_valid_write_fu_816_p18;
reg   [0:0] p_out_4_valid_write_reg_1749;
reg   [0:0] p_out_4_valid_write_reg_1749_pp0_iter3_reg;
reg   [0:0] p_out_4_valid_write_reg_1749_pp0_iter4_reg;
reg   [0:0] p_out_4_valid_write_reg_1749_pp0_iter5_reg;
reg   [0:0] p_out_4_valid_write_reg_1749_pp0_iter6_reg;
reg    ap_block_pp0_stage0_subdone;
wire    grp_genChain_7_fu_446_ap_start;
wire    grp_genChain_7_fu_446_ap_done;
wire    grp_genChain_7_fu_446_ap_idle;
wire    grp_genChain_7_fu_446_ap_ready;
reg    grp_genChain_7_fu_446_ap_ce;
wire   [3:0] grp_genChain_7_fu_446_control_bits_V_127;
wire    grp_genChain_7_fu_446_p_in_0_valid_read;
wire    grp_genChain_7_fu_446_p_in_1_valid_read;
wire    grp_genChain_7_fu_446_p_in_2_valid_read;
wire    grp_genChain_7_fu_446_p_in_3_valid_read;
wire    grp_genChain_7_fu_446_p_in_4_valid_read;
wire    grp_genChain_7_fu_446_p_in_5_valid_read;
wire    grp_genChain_7_fu_446_p_in_6_valid_read;
wire    grp_genChain_7_fu_446_p_in_7_valid_read;
wire    grp_genChain_7_fu_446_p_in_8_valid_read;
wire    grp_genChain_7_fu_446_p_in_9_valid_read;
wire    grp_genChain_7_fu_446_p_in_10_valid_read;
wire    grp_genChain_7_fu_446_p_in_11_valid_read;
wire    grp_genChain_7_fu_446_p_in_12_valid_read;
wire    grp_genChain_7_fu_446_p_in_13_valid_read;
wire    grp_genChain_7_fu_446_p_in_14_valid_read;
wire    grp_genChain_7_fu_446_p_in_15_valid_read;
wire   [15:0] grp_genChain_7_fu_446_ap_return_0;
wire   [15:0] grp_genChain_7_fu_446_ap_return_1;
wire   [0:0] grp_genChain_7_fu_446_ap_return_2;
wire   [15:0] grp_genChain_7_fu_446_ap_return_3;
wire   [15:0] grp_genChain_7_fu_446_ap_return_4;
wire   [0:0] grp_genChain_7_fu_446_ap_return_5;
wire   [15:0] grp_genChain_7_fu_446_ap_return_6;
wire   [15:0] grp_genChain_7_fu_446_ap_return_7;
wire   [0:0] grp_genChain_7_fu_446_ap_return_8;
wire   [15:0] grp_genChain_7_fu_446_ap_return_9;
wire   [15:0] grp_genChain_7_fu_446_ap_return_10;
wire   [0:0] grp_genChain_7_fu_446_ap_return_11;
wire   [15:0] grp_genChain_7_fu_446_ap_return_12;
wire   [15:0] grp_genChain_7_fu_446_ap_return_13;
wire   [0:0] grp_genChain_7_fu_446_ap_return_14;
wire   [15:0] grp_genChain_7_fu_446_ap_return_15;
wire   [15:0] grp_genChain_7_fu_446_ap_return_16;
wire   [0:0] grp_genChain_7_fu_446_ap_return_17;
wire   [15:0] grp_genChain_7_fu_446_ap_return_18;
wire   [15:0] grp_genChain_7_fu_446_ap_return_19;
wire   [0:0] grp_genChain_7_fu_446_ap_return_20;
wire   [15:0] grp_genChain_7_fu_446_ap_return_21;
wire   [15:0] grp_genChain_7_fu_446_ap_return_22;
wire   [0:0] grp_genChain_7_fu_446_ap_return_23;
wire   [15:0] grp_genChain_7_fu_446_ap_return_24;
wire   [15:0] grp_genChain_7_fu_446_ap_return_25;
wire   [0:0] grp_genChain_7_fu_446_ap_return_26;
wire   [15:0] grp_genChain_7_fu_446_ap_return_27;
wire   [15:0] grp_genChain_7_fu_446_ap_return_28;
wire   [0:0] grp_genChain_7_fu_446_ap_return_29;
wire   [15:0] grp_genChain_7_fu_446_ap_return_30;
wire   [15:0] grp_genChain_7_fu_446_ap_return_31;
wire   [0:0] grp_genChain_7_fu_446_ap_return_32;
reg    ap_block_state1_pp0_stage0_iter0_ignore_call73;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call73;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call73;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call73;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call73;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call73;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call73;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call73;
reg    ap_block_pp0_stage0_11001_ignoreCallOp82;
reg    grp_genChain_7_fu_446_ap_start_reg;
wire   [31:0] zext_ln66_fu_519_p1;
wire   [31:0] zext_ln66_10_fu_537_p1;
wire   [31:0] zext_ln66_11_fu_554_p1;
wire   [31:0] zext_ln66_12_fu_761_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to6;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 grp_genChain_7_fu_446_ap_start_reg = 1'b0;
end

genChain_7_controcAy #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
control_delayline_Ar_9_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(4'd15),
    .ce0(control_delayline_Ar_9_ce0),
    .we0(control_delayline_Ar_9_we0),
    .d0(zext_ln66_fu_519_p1),
    .q0(control_delayline_Ar_9_q0)
);

genChain_7_controcAy #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
control_delayline_Ar_57_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(4'd15),
    .ce0(control_delayline_Ar_57_ce0),
    .we0(control_delayline_Ar_57_we0),
    .d0(zext_ln66_10_fu_537_p1),
    .q0(control_delayline_Ar_57_q0)
);

genChain_7_controcAy #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
control_delayline_Ar_59_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(4'd15),
    .ce0(control_delayline_Ar_59_ce0),
    .we0(control_delayline_Ar_59_we0),
    .d0(zext_ln66_11_fu_554_p1),
    .q0(control_delayline_Ar_59_q0)
);

genChain_7_controcAy #(
    .DataWidth( 32 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
control_delayline_Ar_60_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(4'd15),
    .ce0(control_delayline_Ar_60_ce0),
    .we0(control_delayline_Ar_60_we0),
    .d0(zext_ln66_12_fu_761_p1),
    .q0(control_delayline_Ar_60_q0)
);

genChain_7 grp_genChain_7_fu_446(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_genChain_7_fu_446_ap_start),
    .ap_done(grp_genChain_7_fu_446_ap_done),
    .ap_idle(grp_genChain_7_fu_446_ap_idle),
    .ap_ready(grp_genChain_7_fu_446_ap_ready),
    .ap_ce(grp_genChain_7_fu_446_ap_ce),
    .control_bits_V_127(grp_genChain_7_fu_446_control_bits_V_127),
    .p_in_0_sample_M_real_V_read(p_in_0_sample_M_re_reg_1655_pp0_iter1_reg),
    .p_in_1_sample_M_real_V_read(p_in_1_sample_M_re_reg_1646_pp0_iter1_reg),
    .p_in_2_sample_M_real_V_read(p_in_2_sample_M_re_reg_1637_pp0_iter1_reg),
    .p_in_3_sample_M_real_V_read(p_in_3_sample_M_re_reg_1628_pp0_iter1_reg),
    .p_in_4_sample_M_real_V_read(p_in_4_sample_M_re_reg_1619_pp0_iter1_reg),
    .p_in_5_sample_M_real_V_read(p_in_5_sample_M_re_reg_1610_pp0_iter1_reg),
    .p_in_6_sample_M_real_V_read(p_in_6_sample_M_re_reg_1601_pp0_iter1_reg),
    .p_in_7_sample_M_real_V_read(p_in_7_sample_M_re_reg_1592_pp0_iter1_reg),
    .p_in_8_sample_M_real_V_read(p_in_8_sample_M_re_reg_1583_pp0_iter1_reg),
    .p_in_9_sample_M_real_V_read(p_in_9_sample_M_re_reg_1574_pp0_iter1_reg),
    .p_in_10_sample_M_real_V_read(p_in_10_sample_M_r_reg_1565_pp0_iter1_reg),
    .p_in_11_sample_M_real_V_read(p_in_11_sample_M_r_reg_1556_pp0_iter1_reg),
    .p_in_12_sample_M_real_V_read(p_in_12_sample_M_r_reg_1547_pp0_iter1_reg),
    .p_in_13_sample_M_real_V_read(p_in_13_sample_M_r_reg_1538_pp0_iter1_reg),
    .p_in_14_sample_M_real_V_read(p_in_14_sample_M_r_reg_1529_pp0_iter1_reg),
    .p_in_15_sample_M_real_V_read(p_in_15_sample_M_r_reg_1520_pp0_iter1_reg),
    .p_in_0_sample_M_imag_V_read(p_in_0_sample_M_im_reg_1511_pp0_iter1_reg),
    .p_in_1_sample_M_imag_V_read(p_in_1_sample_M_im_reg_1502_pp0_iter1_reg),
    .p_in_2_sample_M_imag_V_read(p_in_2_sample_M_im_reg_1493_pp0_iter1_reg),
    .p_in_3_sample_M_imag_V_read(p_in_3_sample_M_im_reg_1484_pp0_iter1_reg),
    .p_in_4_sample_M_imag_V_read(p_in_4_sample_M_im_reg_1475_pp0_iter1_reg),
    .p_in_5_sample_M_imag_V_read(p_in_5_sample_M_im_reg_1466_pp0_iter1_reg),
    .p_in_6_sample_M_imag_V_read(p_in_6_sample_M_im_reg_1457_pp0_iter1_reg),
    .p_in_7_sample_M_imag_V_read(p_in_7_sample_M_im_reg_1448_pp0_iter1_reg),
    .p_in_8_sample_M_imag_V_read(p_in_8_sample_M_im_reg_1439_pp0_iter1_reg),
    .p_in_9_sample_M_imag_V_read(p_in_9_sample_M_im_reg_1430_pp0_iter1_reg),
    .p_in_10_sample_M_imag_V_read(p_in_10_sample_M_i_reg_1421_pp0_iter1_reg),
    .p_in_11_sample_M_imag_V_read(p_in_11_sample_M_i_reg_1412_pp0_iter1_reg),
    .p_in_12_sample_M_imag_V_read(p_in_12_sample_M_i_reg_1403_pp0_iter1_reg),
    .p_in_13_sample_M_imag_V_read(p_in_13_sample_M_i_reg_1394_pp0_iter1_reg),
    .p_in_14_sample_M_imag_V_read(p_in_14_sample_M_i_reg_1385_pp0_iter1_reg),
    .p_in_15_sample_M_imag_V_read(p_in_15_sample_M_i_reg_1376_pp0_iter1_reg),
    .p_in_0_valid_read(grp_genChain_7_fu_446_p_in_0_valid_read),
    .p_in_1_valid_read(grp_genChain_7_fu_446_p_in_1_valid_read),
    .p_in_2_valid_read(grp_genChain_7_fu_446_p_in_2_valid_read),
    .p_in_3_valid_read(grp_genChain_7_fu_446_p_in_3_valid_read),
    .p_in_4_valid_read(grp_genChain_7_fu_446_p_in_4_valid_read),
    .p_in_5_valid_read(grp_genChain_7_fu_446_p_in_5_valid_read),
    .p_in_6_valid_read(grp_genChain_7_fu_446_p_in_6_valid_read),
    .p_in_7_valid_read(grp_genChain_7_fu_446_p_in_7_valid_read),
    .p_in_8_valid_read(grp_genChain_7_fu_446_p_in_8_valid_read),
    .p_in_9_valid_read(grp_genChain_7_fu_446_p_in_9_valid_read),
    .p_in_10_valid_read(grp_genChain_7_fu_446_p_in_10_valid_read),
    .p_in_11_valid_read(grp_genChain_7_fu_446_p_in_11_valid_read),
    .p_in_12_valid_read(grp_genChain_7_fu_446_p_in_12_valid_read),
    .p_in_13_valid_read(grp_genChain_7_fu_446_p_in_13_valid_read),
    .p_in_14_valid_read(grp_genChain_7_fu_446_p_in_14_valid_read),
    .p_in_15_valid_read(grp_genChain_7_fu_446_p_in_15_valid_read),
    .ap_return_0(grp_genChain_7_fu_446_ap_return_0),
    .ap_return_1(grp_genChain_7_fu_446_ap_return_1),
    .ap_return_2(grp_genChain_7_fu_446_ap_return_2),
    .ap_return_3(grp_genChain_7_fu_446_ap_return_3),
    .ap_return_4(grp_genChain_7_fu_446_ap_return_4),
    .ap_return_5(grp_genChain_7_fu_446_ap_return_5),
    .ap_return_6(grp_genChain_7_fu_446_ap_return_6),
    .ap_return_7(grp_genChain_7_fu_446_ap_return_7),
    .ap_return_8(grp_genChain_7_fu_446_ap_return_8),
    .ap_return_9(grp_genChain_7_fu_446_ap_return_9),
    .ap_return_10(grp_genChain_7_fu_446_ap_return_10),
    .ap_return_11(grp_genChain_7_fu_446_ap_return_11),
    .ap_return_12(grp_genChain_7_fu_446_ap_return_12),
    .ap_return_13(grp_genChain_7_fu_446_ap_return_13),
    .ap_return_14(grp_genChain_7_fu_446_ap_return_14),
    .ap_return_15(grp_genChain_7_fu_446_ap_return_15),
    .ap_return_16(grp_genChain_7_fu_446_ap_return_16),
    .ap_return_17(grp_genChain_7_fu_446_ap_return_17),
    .ap_return_18(grp_genChain_7_fu_446_ap_return_18),
    .ap_return_19(grp_genChain_7_fu_446_ap_return_19),
    .ap_return_20(grp_genChain_7_fu_446_ap_return_20),
    .ap_return_21(grp_genChain_7_fu_446_ap_return_21),
    .ap_return_22(grp_genChain_7_fu_446_ap_return_22),
    .ap_return_23(grp_genChain_7_fu_446_ap_return_23),
    .ap_return_24(grp_genChain_7_fu_446_ap_return_24),
    .ap_return_25(grp_genChain_7_fu_446_ap_return_25),
    .ap_return_26(grp_genChain_7_fu_446_ap_return_26),
    .ap_return_27(grp_genChain_7_fu_446_ap_return_27),
    .ap_return_28(grp_genChain_7_fu_446_ap_return_28),
    .ap_return_29(grp_genChain_7_fu_446_ap_return_29),
    .ap_return_30(grp_genChain_7_fu_446_ap_return_30),
    .ap_return_31(grp_genChain_7_fu_446_ap_return_31),
    .ap_return_32(grp_genChain_7_fu_446_ap_return_32)
);

fft_top_mux_164_11iI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
fft_top_mux_164_11iI_U451(
    .din0(p_in_0_sample_M_re_reg_1655_pp0_iter1_reg),
    .din1(p_in_1_sample_M_re_reg_1646_pp0_iter1_reg),
    .din2(p_in_2_sample_M_re_reg_1637_pp0_iter1_reg),
    .din3(p_in_3_sample_M_re_reg_1628_pp0_iter1_reg),
    .din4(p_in_4_sample_M_re_reg_1619_pp0_iter1_reg),
    .din5(p_in_5_sample_M_re_reg_1610_pp0_iter1_reg),
    .din6(p_in_6_sample_M_re_reg_1601_pp0_iter1_reg),
    .din7(p_in_7_sample_M_re_reg_1592_pp0_iter1_reg),
    .din8(p_in_8_sample_M_re_reg_1583_pp0_iter1_reg),
    .din9(p_in_9_sample_M_re_reg_1574_pp0_iter1_reg),
    .din10(p_in_10_sample_M_r_reg_1565_pp0_iter1_reg),
    .din11(p_in_11_sample_M_r_reg_1556_pp0_iter1_reg),
    .din12(p_in_12_sample_M_r_reg_1547_pp0_iter1_reg),
    .din13(p_in_13_sample_M_r_reg_1538_pp0_iter1_reg),
    .din14(p_in_14_sample_M_r_reg_1529_pp0_iter1_reg),
    .din15(p_in_15_sample_M_r_reg_1520_pp0_iter1_reg),
    .din16(control_bits_V_119_r_reg_1664_pp0_iter1_reg),
    .dout(p_out_1_sample_M_r_fu_572_p18)
);

fft_top_mux_164_11iI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
fft_top_mux_164_11iI_U452(
    .din0(p_in_0_sample_M_im_reg_1511_pp0_iter1_reg),
    .din1(p_in_1_sample_M_im_reg_1502_pp0_iter1_reg),
    .din2(p_in_2_sample_M_im_reg_1493_pp0_iter1_reg),
    .din3(p_in_3_sample_M_im_reg_1484_pp0_iter1_reg),
    .din4(p_in_4_sample_M_im_reg_1475_pp0_iter1_reg),
    .din5(p_in_5_sample_M_im_reg_1466_pp0_iter1_reg),
    .din6(p_in_6_sample_M_im_reg_1457_pp0_iter1_reg),
    .din7(p_in_7_sample_M_im_reg_1448_pp0_iter1_reg),
    .din8(p_in_8_sample_M_im_reg_1439_pp0_iter1_reg),
    .din9(p_in_9_sample_M_im_reg_1430_pp0_iter1_reg),
    .din10(p_in_10_sample_M_i_reg_1421_pp0_iter1_reg),
    .din11(p_in_11_sample_M_i_reg_1412_pp0_iter1_reg),
    .din12(p_in_12_sample_M_i_reg_1403_pp0_iter1_reg),
    .din13(p_in_13_sample_M_i_reg_1394_pp0_iter1_reg),
    .din14(p_in_14_sample_M_i_reg_1385_pp0_iter1_reg),
    .din15(p_in_15_sample_M_i_reg_1376_pp0_iter1_reg),
    .din16(control_bits_V_119_r_reg_1664_pp0_iter1_reg),
    .dout(p_out_1_sample_M_i_fu_593_p18)
);

fft_top_mux_164_12iS #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
fft_top_mux_164_12iS_U453(
    .din0(p_in_0_valid_read_14_reg_1367_pp0_iter1_reg),
    .din1(p_in_1_valid_read81_reg_1358_pp0_iter1_reg),
    .din2(p_in_2_valid_read82_reg_1349_pp0_iter1_reg),
    .din3(p_in_3_valid_read83_reg_1340_pp0_iter1_reg),
    .din4(p_in_4_valid_read84_reg_1331_pp0_iter1_reg),
    .din5(p_in_5_valid_read85_reg_1322_pp0_iter1_reg),
    .din6(p_in_6_valid_read_6_reg_1313_pp0_iter1_reg),
    .din7(p_in_7_valid_read_6_reg_1304_pp0_iter1_reg),
    .din8(p_in_8_valid_read_6_reg_1295_pp0_iter1_reg),
    .din9(p_in_9_valid_read_6_reg_1286_pp0_iter1_reg),
    .din10(p_in_10_valid_read_6_reg_1277_pp0_iter1_reg),
    .din11(p_in_11_valid_read9_reg_1268_pp0_iter1_reg),
    .din12(p_in_12_valid_read9_reg_1259_pp0_iter1_reg),
    .din13(p_in_13_valid_read9_reg_1250_pp0_iter1_reg),
    .din14(p_in_14_valid_read9_reg_1241_pp0_iter1_reg),
    .din15(p_in_15_valid_read9_reg_1232_pp0_iter1_reg),
    .din16(control_bits_V_119_r_reg_1664_pp0_iter1_reg),
    .dout(p_out_1_valid_write_fu_614_p18)
);

fft_top_mux_164_11iI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
fft_top_mux_164_11iI_U454(
    .din0(p_in_0_sample_M_re_reg_1655_pp0_iter1_reg),
    .din1(p_in_1_sample_M_re_reg_1646_pp0_iter1_reg),
    .din2(p_in_2_sample_M_re_reg_1637_pp0_iter1_reg),
    .din3(p_in_3_sample_M_re_reg_1628_pp0_iter1_reg),
    .din4(p_in_4_sample_M_re_reg_1619_pp0_iter1_reg),
    .din5(p_in_5_sample_M_re_reg_1610_pp0_iter1_reg),
    .din6(p_in_6_sample_M_re_reg_1601_pp0_iter1_reg),
    .din7(p_in_7_sample_M_re_reg_1592_pp0_iter1_reg),
    .din8(p_in_8_sample_M_re_reg_1583_pp0_iter1_reg),
    .din9(p_in_9_sample_M_re_reg_1574_pp0_iter1_reg),
    .din10(p_in_10_sample_M_r_reg_1565_pp0_iter1_reg),
    .din11(p_in_11_sample_M_r_reg_1556_pp0_iter1_reg),
    .din12(p_in_12_sample_M_r_reg_1547_pp0_iter1_reg),
    .din13(p_in_13_sample_M_r_reg_1538_pp0_iter1_reg),
    .din14(p_in_14_sample_M_r_reg_1529_pp0_iter1_reg),
    .din15(p_in_15_sample_M_r_reg_1520_pp0_iter1_reg),
    .din16(trunc_ln302_reg_1671_pp0_iter1_reg),
    .dout(p_out_2_sample_M_r_fu_635_p18)
);

fft_top_mux_164_11iI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
fft_top_mux_164_11iI_U455(
    .din0(p_in_0_sample_M_im_reg_1511_pp0_iter1_reg),
    .din1(p_in_1_sample_M_im_reg_1502_pp0_iter1_reg),
    .din2(p_in_2_sample_M_im_reg_1493_pp0_iter1_reg),
    .din3(p_in_3_sample_M_im_reg_1484_pp0_iter1_reg),
    .din4(p_in_4_sample_M_im_reg_1475_pp0_iter1_reg),
    .din5(p_in_5_sample_M_im_reg_1466_pp0_iter1_reg),
    .din6(p_in_6_sample_M_im_reg_1457_pp0_iter1_reg),
    .din7(p_in_7_sample_M_im_reg_1448_pp0_iter1_reg),
    .din8(p_in_8_sample_M_im_reg_1439_pp0_iter1_reg),
    .din9(p_in_9_sample_M_im_reg_1430_pp0_iter1_reg),
    .din10(p_in_10_sample_M_i_reg_1421_pp0_iter1_reg),
    .din11(p_in_11_sample_M_i_reg_1412_pp0_iter1_reg),
    .din12(p_in_12_sample_M_i_reg_1403_pp0_iter1_reg),
    .din13(p_in_13_sample_M_i_reg_1394_pp0_iter1_reg),
    .din14(p_in_14_sample_M_i_reg_1385_pp0_iter1_reg),
    .din15(p_in_15_sample_M_i_reg_1376_pp0_iter1_reg),
    .din16(trunc_ln302_reg_1671_pp0_iter1_reg),
    .dout(p_out_2_sample_M_i_fu_656_p18)
);

fft_top_mux_164_12iS #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
fft_top_mux_164_12iS_U456(
    .din0(p_in_0_valid_read_14_reg_1367_pp0_iter1_reg),
    .din1(p_in_1_valid_read81_reg_1358_pp0_iter1_reg),
    .din2(p_in_2_valid_read82_reg_1349_pp0_iter1_reg),
    .din3(p_in_3_valid_read83_reg_1340_pp0_iter1_reg),
    .din4(p_in_4_valid_read84_reg_1331_pp0_iter1_reg),
    .din5(p_in_5_valid_read85_reg_1322_pp0_iter1_reg),
    .din6(p_in_6_valid_read_6_reg_1313_pp0_iter1_reg),
    .din7(p_in_7_valid_read_6_reg_1304_pp0_iter1_reg),
    .din8(p_in_8_valid_read_6_reg_1295_pp0_iter1_reg),
    .din9(p_in_9_valid_read_6_reg_1286_pp0_iter1_reg),
    .din10(p_in_10_valid_read_6_reg_1277_pp0_iter1_reg),
    .din11(p_in_11_valid_read9_reg_1268_pp0_iter1_reg),
    .din12(p_in_12_valid_read9_reg_1259_pp0_iter1_reg),
    .din13(p_in_13_valid_read9_reg_1250_pp0_iter1_reg),
    .din14(p_in_14_valid_read9_reg_1241_pp0_iter1_reg),
    .din15(p_in_15_valid_read9_reg_1232_pp0_iter1_reg),
    .din16(trunc_ln302_reg_1671_pp0_iter1_reg),
    .dout(p_out_2_valid_write_fu_677_p18)
);

fft_top_mux_164_11iI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
fft_top_mux_164_11iI_U457(
    .din0(p_in_0_sample_M_re_reg_1655_pp0_iter1_reg),
    .din1(p_in_1_sample_M_re_reg_1646_pp0_iter1_reg),
    .din2(p_in_2_sample_M_re_reg_1637_pp0_iter1_reg),
    .din3(p_in_3_sample_M_re_reg_1628_pp0_iter1_reg),
    .din4(p_in_4_sample_M_re_reg_1619_pp0_iter1_reg),
    .din5(p_in_5_sample_M_re_reg_1610_pp0_iter1_reg),
    .din6(p_in_6_sample_M_re_reg_1601_pp0_iter1_reg),
    .din7(p_in_7_sample_M_re_reg_1592_pp0_iter1_reg),
    .din8(p_in_8_sample_M_re_reg_1583_pp0_iter1_reg),
    .din9(p_in_9_sample_M_re_reg_1574_pp0_iter1_reg),
    .din10(p_in_10_sample_M_r_reg_1565_pp0_iter1_reg),
    .din11(p_in_11_sample_M_r_reg_1556_pp0_iter1_reg),
    .din12(p_in_12_sample_M_r_reg_1547_pp0_iter1_reg),
    .din13(p_in_13_sample_M_r_reg_1538_pp0_iter1_reg),
    .din14(p_in_14_sample_M_r_reg_1529_pp0_iter1_reg),
    .din15(p_in_15_sample_M_r_reg_1520_pp0_iter1_reg),
    .din16(trunc_ln302_10_reg_1679),
    .dout(p_out_3_sample_M_r_fu_698_p18)
);

fft_top_mux_164_11iI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
fft_top_mux_164_11iI_U458(
    .din0(p_in_0_sample_M_im_reg_1511_pp0_iter1_reg),
    .din1(p_in_1_sample_M_im_reg_1502_pp0_iter1_reg),
    .din2(p_in_2_sample_M_im_reg_1493_pp0_iter1_reg),
    .din3(p_in_3_sample_M_im_reg_1484_pp0_iter1_reg),
    .din4(p_in_4_sample_M_im_reg_1475_pp0_iter1_reg),
    .din5(p_in_5_sample_M_im_reg_1466_pp0_iter1_reg),
    .din6(p_in_6_sample_M_im_reg_1457_pp0_iter1_reg),
    .din7(p_in_7_sample_M_im_reg_1448_pp0_iter1_reg),
    .din8(p_in_8_sample_M_im_reg_1439_pp0_iter1_reg),
    .din9(p_in_9_sample_M_im_reg_1430_pp0_iter1_reg),
    .din10(p_in_10_sample_M_i_reg_1421_pp0_iter1_reg),
    .din11(p_in_11_sample_M_i_reg_1412_pp0_iter1_reg),
    .din12(p_in_12_sample_M_i_reg_1403_pp0_iter1_reg),
    .din13(p_in_13_sample_M_i_reg_1394_pp0_iter1_reg),
    .din14(p_in_14_sample_M_i_reg_1385_pp0_iter1_reg),
    .din15(p_in_15_sample_M_i_reg_1376_pp0_iter1_reg),
    .din16(trunc_ln302_10_reg_1679),
    .dout(p_out_3_sample_M_i_fu_719_p18)
);

fft_top_mux_164_12iS #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
fft_top_mux_164_12iS_U459(
    .din0(p_in_0_valid_read_14_reg_1367_pp0_iter1_reg),
    .din1(p_in_1_valid_read81_reg_1358_pp0_iter1_reg),
    .din2(p_in_2_valid_read82_reg_1349_pp0_iter1_reg),
    .din3(p_in_3_valid_read83_reg_1340_pp0_iter1_reg),
    .din4(p_in_4_valid_read84_reg_1331_pp0_iter1_reg),
    .din5(p_in_5_valid_read85_reg_1322_pp0_iter1_reg),
    .din6(p_in_6_valid_read_6_reg_1313_pp0_iter1_reg),
    .din7(p_in_7_valid_read_6_reg_1304_pp0_iter1_reg),
    .din8(p_in_8_valid_read_6_reg_1295_pp0_iter1_reg),
    .din9(p_in_9_valid_read_6_reg_1286_pp0_iter1_reg),
    .din10(p_in_10_valid_read_6_reg_1277_pp0_iter1_reg),
    .din11(p_in_11_valid_read9_reg_1268_pp0_iter1_reg),
    .din12(p_in_12_valid_read9_reg_1259_pp0_iter1_reg),
    .din13(p_in_13_valid_read9_reg_1250_pp0_iter1_reg),
    .din14(p_in_14_valid_read9_reg_1241_pp0_iter1_reg),
    .din15(p_in_15_valid_read9_reg_1232_pp0_iter1_reg),
    .din16(trunc_ln302_10_reg_1679),
    .dout(p_out_3_valid_write_fu_740_p18)
);

fft_top_mux_164_11iI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
fft_top_mux_164_11iI_U460(
    .din0(p_in_0_sample_M_re_reg_1655_pp0_iter1_reg),
    .din1(p_in_1_sample_M_re_reg_1646_pp0_iter1_reg),
    .din2(p_in_2_sample_M_re_reg_1637_pp0_iter1_reg),
    .din3(p_in_3_sample_M_re_reg_1628_pp0_iter1_reg),
    .din4(p_in_4_sample_M_re_reg_1619_pp0_iter1_reg),
    .din5(p_in_5_sample_M_re_reg_1610_pp0_iter1_reg),
    .din6(p_in_6_sample_M_re_reg_1601_pp0_iter1_reg),
    .din7(p_in_7_sample_M_re_reg_1592_pp0_iter1_reg),
    .din8(p_in_8_sample_M_re_reg_1583_pp0_iter1_reg),
    .din9(p_in_9_sample_M_re_reg_1574_pp0_iter1_reg),
    .din10(p_in_10_sample_M_r_reg_1565_pp0_iter1_reg),
    .din11(p_in_11_sample_M_r_reg_1556_pp0_iter1_reg),
    .din12(p_in_12_sample_M_r_reg_1547_pp0_iter1_reg),
    .din13(p_in_13_sample_M_r_reg_1538_pp0_iter1_reg),
    .din14(p_in_14_sample_M_r_reg_1529_pp0_iter1_reg),
    .din15(p_in_15_sample_M_r_reg_1520_pp0_iter1_reg),
    .din16(trunc_ln302_11_reg_1686),
    .dout(p_out_4_sample_M_r_fu_774_p18)
);

fft_top_mux_164_11iI #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 16 ),
    .din9_WIDTH( 16 ),
    .din10_WIDTH( 16 ),
    .din11_WIDTH( 16 ),
    .din12_WIDTH( 16 ),
    .din13_WIDTH( 16 ),
    .din14_WIDTH( 16 ),
    .din15_WIDTH( 16 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 16 ))
fft_top_mux_164_11iI_U461(
    .din0(p_in_0_sample_M_im_reg_1511_pp0_iter1_reg),
    .din1(p_in_1_sample_M_im_reg_1502_pp0_iter1_reg),
    .din2(p_in_2_sample_M_im_reg_1493_pp0_iter1_reg),
    .din3(p_in_3_sample_M_im_reg_1484_pp0_iter1_reg),
    .din4(p_in_4_sample_M_im_reg_1475_pp0_iter1_reg),
    .din5(p_in_5_sample_M_im_reg_1466_pp0_iter1_reg),
    .din6(p_in_6_sample_M_im_reg_1457_pp0_iter1_reg),
    .din7(p_in_7_sample_M_im_reg_1448_pp0_iter1_reg),
    .din8(p_in_8_sample_M_im_reg_1439_pp0_iter1_reg),
    .din9(p_in_9_sample_M_im_reg_1430_pp0_iter1_reg),
    .din10(p_in_10_sample_M_i_reg_1421_pp0_iter1_reg),
    .din11(p_in_11_sample_M_i_reg_1412_pp0_iter1_reg),
    .din12(p_in_12_sample_M_i_reg_1403_pp0_iter1_reg),
    .din13(p_in_13_sample_M_i_reg_1394_pp0_iter1_reg),
    .din14(p_in_14_sample_M_i_reg_1385_pp0_iter1_reg),
    .din15(p_in_15_sample_M_i_reg_1376_pp0_iter1_reg),
    .din16(trunc_ln302_11_reg_1686),
    .dout(p_out_4_sample_M_i_fu_795_p18)
);

fft_top_mux_164_12iS #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 1 ),
    .din1_WIDTH( 1 ),
    .din2_WIDTH( 1 ),
    .din3_WIDTH( 1 ),
    .din4_WIDTH( 1 ),
    .din5_WIDTH( 1 ),
    .din6_WIDTH( 1 ),
    .din7_WIDTH( 1 ),
    .din8_WIDTH( 1 ),
    .din9_WIDTH( 1 ),
    .din10_WIDTH( 1 ),
    .din11_WIDTH( 1 ),
    .din12_WIDTH( 1 ),
    .din13_WIDTH( 1 ),
    .din14_WIDTH( 1 ),
    .din15_WIDTH( 1 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 1 ))
fft_top_mux_164_12iS_U462(
    .din0(p_in_0_valid_read_14_reg_1367_pp0_iter1_reg),
    .din1(p_in_1_valid_read81_reg_1358_pp0_iter1_reg),
    .din2(p_in_2_valid_read82_reg_1349_pp0_iter1_reg),
    .din3(p_in_3_valid_read83_reg_1340_pp0_iter1_reg),
    .din4(p_in_4_valid_read84_reg_1331_pp0_iter1_reg),
    .din5(p_in_5_valid_read85_reg_1322_pp0_iter1_reg),
    .din6(p_in_6_valid_read_6_reg_1313_pp0_iter1_reg),
    .din7(p_in_7_valid_read_6_reg_1304_pp0_iter1_reg),
    .din8(p_in_8_valid_read_6_reg_1295_pp0_iter1_reg),
    .din9(p_in_9_valid_read_6_reg_1286_pp0_iter1_reg),
    .din10(p_in_10_valid_read_6_reg_1277_pp0_iter1_reg),
    .din11(p_in_11_valid_read9_reg_1268_pp0_iter1_reg),
    .din12(p_in_12_valid_read9_reg_1259_pp0_iter1_reg),
    .din13(p_in_13_valid_read9_reg_1250_pp0_iter1_reg),
    .din14(p_in_14_valid_read9_reg_1241_pp0_iter1_reg),
    .din15(p_in_15_valid_read9_reg_1232_pp0_iter1_reg),
    .din16(trunc_ln302_11_reg_1686),
    .dout(p_out_4_valid_write_fu_816_p18)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_genChain_7_fu_446_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_genChain_7_fu_446_ap_start_reg <= 1'b1;
        end else if ((grp_genChain_7_fu_446_ap_ready == 1'b1)) begin
            grp_genChain_7_fu_446_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        control_bits_V_119_r_reg_1664 <= control_bits_V_119;
        control_bits_V_119_r_reg_1664_pp0_iter1_reg <= control_bits_V_119_r_reg_1664;
        p_in_0_sample_M_im_reg_1511 <= p_in_0_sample_M_imag_V_read;
        p_in_0_sample_M_im_reg_1511_pp0_iter1_reg <= p_in_0_sample_M_im_reg_1511;
        p_in_0_sample_M_re_reg_1655 <= p_in_0_sample_M_real_V_read;
        p_in_0_sample_M_re_reg_1655_pp0_iter1_reg <= p_in_0_sample_M_re_reg_1655;
        p_in_0_valid_read_14_reg_1367 <= p_in_0_valid_read;
        p_in_0_valid_read_14_reg_1367_pp0_iter1_reg <= p_in_0_valid_read_14_reg_1367;
        p_in_10_sample_M_i_reg_1421 <= p_in_10_sample_M_imag_V_read;
        p_in_10_sample_M_i_reg_1421_pp0_iter1_reg <= p_in_10_sample_M_i_reg_1421;
        p_in_10_sample_M_r_reg_1565 <= p_in_10_sample_M_real_V_read;
        p_in_10_sample_M_r_reg_1565_pp0_iter1_reg <= p_in_10_sample_M_r_reg_1565;
        p_in_10_valid_read_6_reg_1277 <= p_in_10_valid_read;
        p_in_10_valid_read_6_reg_1277_pp0_iter1_reg <= p_in_10_valid_read_6_reg_1277;
        p_in_11_sample_M_i_reg_1412 <= p_in_11_sample_M_imag_V_read;
        p_in_11_sample_M_i_reg_1412_pp0_iter1_reg <= p_in_11_sample_M_i_reg_1412;
        p_in_11_sample_M_r_reg_1556 <= p_in_11_sample_M_real_V_read;
        p_in_11_sample_M_r_reg_1556_pp0_iter1_reg <= p_in_11_sample_M_r_reg_1556;
        p_in_11_valid_read9_reg_1268 <= p_in_11_valid_read;
        p_in_11_valid_read9_reg_1268_pp0_iter1_reg <= p_in_11_valid_read9_reg_1268;
        p_in_12_sample_M_i_reg_1403 <= p_in_12_sample_M_imag_V_read;
        p_in_12_sample_M_i_reg_1403_pp0_iter1_reg <= p_in_12_sample_M_i_reg_1403;
        p_in_12_sample_M_r_reg_1547 <= p_in_12_sample_M_real_V_read;
        p_in_12_sample_M_r_reg_1547_pp0_iter1_reg <= p_in_12_sample_M_r_reg_1547;
        p_in_12_valid_read9_reg_1259 <= p_in_12_valid_read;
        p_in_12_valid_read9_reg_1259_pp0_iter1_reg <= p_in_12_valid_read9_reg_1259;
        p_in_13_sample_M_i_reg_1394 <= p_in_13_sample_M_imag_V_read;
        p_in_13_sample_M_i_reg_1394_pp0_iter1_reg <= p_in_13_sample_M_i_reg_1394;
        p_in_13_sample_M_r_reg_1538 <= p_in_13_sample_M_real_V_read;
        p_in_13_sample_M_r_reg_1538_pp0_iter1_reg <= p_in_13_sample_M_r_reg_1538;
        p_in_13_valid_read9_reg_1250 <= p_in_13_valid_read;
        p_in_13_valid_read9_reg_1250_pp0_iter1_reg <= p_in_13_valid_read9_reg_1250;
        p_in_14_sample_M_i_reg_1385 <= p_in_14_sample_M_imag_V_read;
        p_in_14_sample_M_i_reg_1385_pp0_iter1_reg <= p_in_14_sample_M_i_reg_1385;
        p_in_14_sample_M_r_reg_1529 <= p_in_14_sample_M_real_V_read;
        p_in_14_sample_M_r_reg_1529_pp0_iter1_reg <= p_in_14_sample_M_r_reg_1529;
        p_in_14_valid_read9_reg_1241 <= p_in_14_valid_read;
        p_in_14_valid_read9_reg_1241_pp0_iter1_reg <= p_in_14_valid_read9_reg_1241;
        p_in_15_sample_M_i_reg_1376 <= p_in_15_sample_M_imag_V_read;
        p_in_15_sample_M_i_reg_1376_pp0_iter1_reg <= p_in_15_sample_M_i_reg_1376;
        p_in_15_sample_M_r_reg_1520 <= p_in_15_sample_M_real_V_read;
        p_in_15_sample_M_r_reg_1520_pp0_iter1_reg <= p_in_15_sample_M_r_reg_1520;
        p_in_15_valid_read9_reg_1232 <= p_in_15_valid_read;
        p_in_15_valid_read9_reg_1232_pp0_iter1_reg <= p_in_15_valid_read9_reg_1232;
        p_in_1_sample_M_im_reg_1502 <= p_in_1_sample_M_imag_V_read;
        p_in_1_sample_M_im_reg_1502_pp0_iter1_reg <= p_in_1_sample_M_im_reg_1502;
        p_in_1_sample_M_re_reg_1646 <= p_in_1_sample_M_real_V_read;
        p_in_1_sample_M_re_reg_1646_pp0_iter1_reg <= p_in_1_sample_M_re_reg_1646;
        p_in_1_valid_read81_reg_1358 <= p_in_1_valid_read;
        p_in_1_valid_read81_reg_1358_pp0_iter1_reg <= p_in_1_valid_read81_reg_1358;
        p_in_2_sample_M_im_reg_1493 <= p_in_2_sample_M_imag_V_read;
        p_in_2_sample_M_im_reg_1493_pp0_iter1_reg <= p_in_2_sample_M_im_reg_1493;
        p_in_2_sample_M_re_reg_1637 <= p_in_2_sample_M_real_V_read;
        p_in_2_sample_M_re_reg_1637_pp0_iter1_reg <= p_in_2_sample_M_re_reg_1637;
        p_in_2_valid_read82_reg_1349 <= p_in_2_valid_read;
        p_in_2_valid_read82_reg_1349_pp0_iter1_reg <= p_in_2_valid_read82_reg_1349;
        p_in_3_sample_M_im_reg_1484 <= p_in_3_sample_M_imag_V_read;
        p_in_3_sample_M_im_reg_1484_pp0_iter1_reg <= p_in_3_sample_M_im_reg_1484;
        p_in_3_sample_M_re_reg_1628 <= p_in_3_sample_M_real_V_read;
        p_in_3_sample_M_re_reg_1628_pp0_iter1_reg <= p_in_3_sample_M_re_reg_1628;
        p_in_3_valid_read83_reg_1340 <= p_in_3_valid_read;
        p_in_3_valid_read83_reg_1340_pp0_iter1_reg <= p_in_3_valid_read83_reg_1340;
        p_in_4_sample_M_im_reg_1475 <= p_in_4_sample_M_imag_V_read;
        p_in_4_sample_M_im_reg_1475_pp0_iter1_reg <= p_in_4_sample_M_im_reg_1475;
        p_in_4_sample_M_re_reg_1619 <= p_in_4_sample_M_real_V_read;
        p_in_4_sample_M_re_reg_1619_pp0_iter1_reg <= p_in_4_sample_M_re_reg_1619;
        p_in_4_valid_read84_reg_1331 <= p_in_4_valid_read;
        p_in_4_valid_read84_reg_1331_pp0_iter1_reg <= p_in_4_valid_read84_reg_1331;
        p_in_5_sample_M_im_reg_1466 <= p_in_5_sample_M_imag_V_read;
        p_in_5_sample_M_im_reg_1466_pp0_iter1_reg <= p_in_5_sample_M_im_reg_1466;
        p_in_5_sample_M_re_reg_1610 <= p_in_5_sample_M_real_V_read;
        p_in_5_sample_M_re_reg_1610_pp0_iter1_reg <= p_in_5_sample_M_re_reg_1610;
        p_in_5_valid_read85_reg_1322 <= p_in_5_valid_read;
        p_in_5_valid_read85_reg_1322_pp0_iter1_reg <= p_in_5_valid_read85_reg_1322;
        p_in_6_sample_M_im_reg_1457 <= p_in_6_sample_M_imag_V_read;
        p_in_6_sample_M_im_reg_1457_pp0_iter1_reg <= p_in_6_sample_M_im_reg_1457;
        p_in_6_sample_M_re_reg_1601 <= p_in_6_sample_M_real_V_read;
        p_in_6_sample_M_re_reg_1601_pp0_iter1_reg <= p_in_6_sample_M_re_reg_1601;
        p_in_6_valid_read_6_reg_1313 <= p_in_6_valid_read;
        p_in_6_valid_read_6_reg_1313_pp0_iter1_reg <= p_in_6_valid_read_6_reg_1313;
        p_in_7_sample_M_im_reg_1448 <= p_in_7_sample_M_imag_V_read;
        p_in_7_sample_M_im_reg_1448_pp0_iter1_reg <= p_in_7_sample_M_im_reg_1448;
        p_in_7_sample_M_re_reg_1592 <= p_in_7_sample_M_real_V_read;
        p_in_7_sample_M_re_reg_1592_pp0_iter1_reg <= p_in_7_sample_M_re_reg_1592;
        p_in_7_valid_read_6_reg_1304 <= p_in_7_valid_read;
        p_in_7_valid_read_6_reg_1304_pp0_iter1_reg <= p_in_7_valid_read_6_reg_1304;
        p_in_8_sample_M_im_reg_1439 <= p_in_8_sample_M_imag_V_read;
        p_in_8_sample_M_im_reg_1439_pp0_iter1_reg <= p_in_8_sample_M_im_reg_1439;
        p_in_8_sample_M_re_reg_1583 <= p_in_8_sample_M_real_V_read;
        p_in_8_sample_M_re_reg_1583_pp0_iter1_reg <= p_in_8_sample_M_re_reg_1583;
        p_in_8_valid_read_6_reg_1295 <= p_in_8_valid_read;
        p_in_8_valid_read_6_reg_1295_pp0_iter1_reg <= p_in_8_valid_read_6_reg_1295;
        p_in_9_sample_M_im_reg_1430 <= p_in_9_sample_M_imag_V_read;
        p_in_9_sample_M_im_reg_1430_pp0_iter1_reg <= p_in_9_sample_M_im_reg_1430;
        p_in_9_sample_M_re_reg_1574 <= p_in_9_sample_M_real_V_read;
        p_in_9_sample_M_re_reg_1574_pp0_iter1_reg <= p_in_9_sample_M_re_reg_1574;
        p_in_9_valid_read_6_reg_1286 <= p_in_9_valid_read;
        p_in_9_valid_read_6_reg_1286_pp0_iter1_reg <= p_in_9_valid_read_6_reg_1286;
        trunc_ln302_10_reg_1679 <= trunc_ln302_10_fu_550_p1;
        trunc_ln302_11_reg_1686 <= trunc_ln302_11_fu_568_p1;
        trunc_ln302_reg_1671 <= trunc_ln302_fu_533_p1;
        trunc_ln302_reg_1671_pp0_iter1_reg <= trunc_ln302_reg_1671;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_out_1_sample_M_i_reg_1699 <= p_out_1_sample_M_i_fu_593_p18;
        p_out_1_sample_M_i_reg_1699_pp0_iter3_reg <= p_out_1_sample_M_i_reg_1699;
        p_out_1_sample_M_i_reg_1699_pp0_iter4_reg <= p_out_1_sample_M_i_reg_1699_pp0_iter3_reg;
        p_out_1_sample_M_i_reg_1699_pp0_iter5_reg <= p_out_1_sample_M_i_reg_1699_pp0_iter4_reg;
        p_out_1_sample_M_i_reg_1699_pp0_iter6_reg <= p_out_1_sample_M_i_reg_1699_pp0_iter5_reg;
        p_out_1_sample_M_r_reg_1694 <= p_out_1_sample_M_r_fu_572_p18;
        p_out_1_sample_M_r_reg_1694_pp0_iter3_reg <= p_out_1_sample_M_r_reg_1694;
        p_out_1_sample_M_r_reg_1694_pp0_iter4_reg <= p_out_1_sample_M_r_reg_1694_pp0_iter3_reg;
        p_out_1_sample_M_r_reg_1694_pp0_iter5_reg <= p_out_1_sample_M_r_reg_1694_pp0_iter4_reg;
        p_out_1_sample_M_r_reg_1694_pp0_iter6_reg <= p_out_1_sample_M_r_reg_1694_pp0_iter5_reg;
        p_out_1_valid_write_reg_1704 <= p_out_1_valid_write_fu_614_p18;
        p_out_1_valid_write_reg_1704_pp0_iter3_reg <= p_out_1_valid_write_reg_1704;
        p_out_1_valid_write_reg_1704_pp0_iter4_reg <= p_out_1_valid_write_reg_1704_pp0_iter3_reg;
        p_out_1_valid_write_reg_1704_pp0_iter5_reg <= p_out_1_valid_write_reg_1704_pp0_iter4_reg;
        p_out_1_valid_write_reg_1704_pp0_iter6_reg <= p_out_1_valid_write_reg_1704_pp0_iter5_reg;
        p_out_2_sample_M_i_reg_1714 <= p_out_2_sample_M_i_fu_656_p18;
        p_out_2_sample_M_i_reg_1714_pp0_iter3_reg <= p_out_2_sample_M_i_reg_1714;
        p_out_2_sample_M_i_reg_1714_pp0_iter4_reg <= p_out_2_sample_M_i_reg_1714_pp0_iter3_reg;
        p_out_2_sample_M_i_reg_1714_pp0_iter5_reg <= p_out_2_sample_M_i_reg_1714_pp0_iter4_reg;
        p_out_2_sample_M_i_reg_1714_pp0_iter6_reg <= p_out_2_sample_M_i_reg_1714_pp0_iter5_reg;
        p_out_2_sample_M_r_reg_1709 <= p_out_2_sample_M_r_fu_635_p18;
        p_out_2_sample_M_r_reg_1709_pp0_iter3_reg <= p_out_2_sample_M_r_reg_1709;
        p_out_2_sample_M_r_reg_1709_pp0_iter4_reg <= p_out_2_sample_M_r_reg_1709_pp0_iter3_reg;
        p_out_2_sample_M_r_reg_1709_pp0_iter5_reg <= p_out_2_sample_M_r_reg_1709_pp0_iter4_reg;
        p_out_2_sample_M_r_reg_1709_pp0_iter6_reg <= p_out_2_sample_M_r_reg_1709_pp0_iter5_reg;
        p_out_2_valid_write_reg_1719 <= p_out_2_valid_write_fu_677_p18;
        p_out_2_valid_write_reg_1719_pp0_iter3_reg <= p_out_2_valid_write_reg_1719;
        p_out_2_valid_write_reg_1719_pp0_iter4_reg <= p_out_2_valid_write_reg_1719_pp0_iter3_reg;
        p_out_2_valid_write_reg_1719_pp0_iter5_reg <= p_out_2_valid_write_reg_1719_pp0_iter4_reg;
        p_out_2_valid_write_reg_1719_pp0_iter6_reg <= p_out_2_valid_write_reg_1719_pp0_iter5_reg;
        p_out_3_sample_M_i_reg_1729 <= p_out_3_sample_M_i_fu_719_p18;
        p_out_3_sample_M_i_reg_1729_pp0_iter3_reg <= p_out_3_sample_M_i_reg_1729;
        p_out_3_sample_M_i_reg_1729_pp0_iter4_reg <= p_out_3_sample_M_i_reg_1729_pp0_iter3_reg;
        p_out_3_sample_M_i_reg_1729_pp0_iter5_reg <= p_out_3_sample_M_i_reg_1729_pp0_iter4_reg;
        p_out_3_sample_M_i_reg_1729_pp0_iter6_reg <= p_out_3_sample_M_i_reg_1729_pp0_iter5_reg;
        p_out_3_sample_M_r_reg_1724 <= p_out_3_sample_M_r_fu_698_p18;
        p_out_3_sample_M_r_reg_1724_pp0_iter3_reg <= p_out_3_sample_M_r_reg_1724;
        p_out_3_sample_M_r_reg_1724_pp0_iter4_reg <= p_out_3_sample_M_r_reg_1724_pp0_iter3_reg;
        p_out_3_sample_M_r_reg_1724_pp0_iter5_reg <= p_out_3_sample_M_r_reg_1724_pp0_iter4_reg;
        p_out_3_sample_M_r_reg_1724_pp0_iter6_reg <= p_out_3_sample_M_r_reg_1724_pp0_iter5_reg;
        p_out_3_valid_write_reg_1734 <= p_out_3_valid_write_fu_740_p18;
        p_out_3_valid_write_reg_1734_pp0_iter3_reg <= p_out_3_valid_write_reg_1734;
        p_out_3_valid_write_reg_1734_pp0_iter4_reg <= p_out_3_valid_write_reg_1734_pp0_iter3_reg;
        p_out_3_valid_write_reg_1734_pp0_iter5_reg <= p_out_3_valid_write_reg_1734_pp0_iter4_reg;
        p_out_3_valid_write_reg_1734_pp0_iter6_reg <= p_out_3_valid_write_reg_1734_pp0_iter5_reg;
        p_out_4_sample_M_i_reg_1744 <= p_out_4_sample_M_i_fu_795_p18;
        p_out_4_sample_M_i_reg_1744_pp0_iter3_reg <= p_out_4_sample_M_i_reg_1744;
        p_out_4_sample_M_i_reg_1744_pp0_iter4_reg <= p_out_4_sample_M_i_reg_1744_pp0_iter3_reg;
        p_out_4_sample_M_i_reg_1744_pp0_iter5_reg <= p_out_4_sample_M_i_reg_1744_pp0_iter4_reg;
        p_out_4_sample_M_i_reg_1744_pp0_iter6_reg <= p_out_4_sample_M_i_reg_1744_pp0_iter5_reg;
        p_out_4_sample_M_r_reg_1739 <= p_out_4_sample_M_r_fu_774_p18;
        p_out_4_sample_M_r_reg_1739_pp0_iter3_reg <= p_out_4_sample_M_r_reg_1739;
        p_out_4_sample_M_r_reg_1739_pp0_iter4_reg <= p_out_4_sample_M_r_reg_1739_pp0_iter3_reg;
        p_out_4_sample_M_r_reg_1739_pp0_iter5_reg <= p_out_4_sample_M_r_reg_1739_pp0_iter4_reg;
        p_out_4_sample_M_r_reg_1739_pp0_iter6_reg <= p_out_4_sample_M_r_reg_1739_pp0_iter5_reg;
        p_out_4_valid_write_reg_1749 <= p_out_4_valid_write_fu_816_p18;
        p_out_4_valid_write_reg_1749_pp0_iter3_reg <= p_out_4_valid_write_reg_1749;
        p_out_4_valid_write_reg_1749_pp0_iter4_reg <= p_out_4_valid_write_reg_1749_pp0_iter3_reg;
        p_out_4_valid_write_reg_1749_pp0_iter5_reg <= p_out_4_valid_write_reg_1749_pp0_iter4_reg;
        p_out_4_valid_write_reg_1749_pp0_iter6_reg <= p_out_4_valid_write_reg_1749_pp0_iter5_reg;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter7 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to6 = 1'b1;
    end else begin
        ap_idle_pp0_0to6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        control_delayline_Ar_57_ce0 = 1'd1;
    end else begin
        control_delayline_Ar_57_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        control_delayline_Ar_57_we0 = 1'd1;
    end else begin
        control_delayline_Ar_57_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        control_delayline_Ar_59_ce0 = 1'd1;
    end else begin
        control_delayline_Ar_59_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        control_delayline_Ar_59_we0 = 1'd1;
    end else begin
        control_delayline_Ar_59_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        control_delayline_Ar_60_ce0 = 1'd1;
    end else begin
        control_delayline_Ar_60_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        control_delayline_Ar_60_we0 = 1'd1;
    end else begin
        control_delayline_Ar_60_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        control_delayline_Ar_9_ce0 = 1'd1;
    end else begin
        control_delayline_Ar_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        control_delayline_Ar_9_we0 = 1'd1;
    end else begin
        control_delayline_Ar_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp82) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_genChain_7_fu_446_ap_ce = 1'b1;
    end else begin
        grp_genChain_7_fu_446_ap_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_ignoreCallOp82 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0_ignore_call73 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call73 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = p_out_1_sample_M_r_reg_1694_pp0_iter6_reg;

assign ap_return_1 = p_out_1_sample_M_i_reg_1699_pp0_iter6_reg;

assign ap_return_10 = p_out_4_sample_M_i_reg_1744_pp0_iter6_reg;

assign ap_return_11 = p_out_4_valid_write_reg_1749_pp0_iter6_reg;

assign ap_return_12 = grp_genChain_7_fu_446_ap_return_0;

assign ap_return_13 = grp_genChain_7_fu_446_ap_return_1;

assign ap_return_14 = grp_genChain_7_fu_446_ap_return_2;

assign ap_return_15 = grp_genChain_7_fu_446_ap_return_3;

assign ap_return_16 = grp_genChain_7_fu_446_ap_return_4;

assign ap_return_17 = grp_genChain_7_fu_446_ap_return_5;

assign ap_return_18 = grp_genChain_7_fu_446_ap_return_6;

assign ap_return_19 = grp_genChain_7_fu_446_ap_return_7;

assign ap_return_2 = p_out_1_valid_write_reg_1704_pp0_iter6_reg;

assign ap_return_20 = grp_genChain_7_fu_446_ap_return_8;

assign ap_return_21 = grp_genChain_7_fu_446_ap_return_9;

assign ap_return_22 = grp_genChain_7_fu_446_ap_return_10;

assign ap_return_23 = grp_genChain_7_fu_446_ap_return_11;

assign ap_return_24 = grp_genChain_7_fu_446_ap_return_12;

assign ap_return_25 = grp_genChain_7_fu_446_ap_return_13;

assign ap_return_26 = grp_genChain_7_fu_446_ap_return_14;

assign ap_return_27 = grp_genChain_7_fu_446_ap_return_15;

assign ap_return_28 = grp_genChain_7_fu_446_ap_return_16;

assign ap_return_29 = grp_genChain_7_fu_446_ap_return_17;

assign ap_return_3 = p_out_2_sample_M_r_reg_1709_pp0_iter6_reg;

assign ap_return_30 = grp_genChain_7_fu_446_ap_return_18;

assign ap_return_31 = grp_genChain_7_fu_446_ap_return_19;

assign ap_return_32 = grp_genChain_7_fu_446_ap_return_20;

assign ap_return_33 = grp_genChain_7_fu_446_ap_return_21;

assign ap_return_34 = grp_genChain_7_fu_446_ap_return_22;

assign ap_return_35 = grp_genChain_7_fu_446_ap_return_23;

assign ap_return_36 = grp_genChain_7_fu_446_ap_return_24;

assign ap_return_37 = grp_genChain_7_fu_446_ap_return_25;

assign ap_return_38 = grp_genChain_7_fu_446_ap_return_26;

assign ap_return_39 = grp_genChain_7_fu_446_ap_return_27;

assign ap_return_4 = p_out_2_sample_M_i_reg_1714_pp0_iter6_reg;

assign ap_return_40 = grp_genChain_7_fu_446_ap_return_28;

assign ap_return_41 = grp_genChain_7_fu_446_ap_return_29;

assign ap_return_42 = grp_genChain_7_fu_446_ap_return_30;

assign ap_return_43 = grp_genChain_7_fu_446_ap_return_31;

assign ap_return_44 = grp_genChain_7_fu_446_ap_return_32;

assign ap_return_5 = p_out_2_valid_write_reg_1719_pp0_iter6_reg;

assign ap_return_6 = p_out_3_sample_M_r_reg_1724_pp0_iter6_reg;

assign ap_return_7 = p_out_3_sample_M_i_reg_1729_pp0_iter6_reg;

assign ap_return_8 = p_out_3_valid_write_reg_1734_pp0_iter6_reg;

assign ap_return_9 = p_out_4_sample_M_r_reg_1739_pp0_iter6_reg;

assign grp_genChain_7_fu_446_ap_start = grp_genChain_7_fu_446_ap_start_reg;

assign grp_genChain_7_fu_446_control_bits_V_127 = control_delayline_Ar_60_q0[3:0];

assign grp_genChain_7_fu_446_p_in_0_valid_read = p_in_0_valid_read_14_reg_1367_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_10_valid_read = p_in_10_valid_read_6_reg_1277_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_11_valid_read = p_in_11_valid_read9_reg_1268_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_12_valid_read = p_in_12_valid_read9_reg_1259_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_13_valid_read = p_in_13_valid_read9_reg_1250_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_14_valid_read = p_in_14_valid_read9_reg_1241_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_15_valid_read = p_in_15_valid_read9_reg_1232_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_1_valid_read = p_in_1_valid_read81_reg_1358_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_2_valid_read = p_in_2_valid_read82_reg_1349_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_3_valid_read = p_in_3_valid_read83_reg_1340_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_4_valid_read = p_in_4_valid_read84_reg_1331_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_5_valid_read = p_in_5_valid_read85_reg_1322_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_6_valid_read = p_in_6_valid_read_6_reg_1313_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_7_valid_read = p_in_7_valid_read_6_reg_1304_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_8_valid_read = p_in_8_valid_read_6_reg_1295_pp0_iter1_reg;

assign grp_genChain_7_fu_446_p_in_9_valid_read = p_in_9_valid_read_6_reg_1286_pp0_iter1_reg;

assign trunc_ln302_10_fu_550_p1 = control_delayline_Ar_57_q0[3:0];

assign trunc_ln302_11_fu_568_p1 = control_delayline_Ar_59_q0[3:0];

assign trunc_ln302_fu_533_p1 = control_delayline_Ar_9_q0[3:0];

assign zext_ln66_10_fu_537_p1 = trunc_ln302_reg_1671;

assign zext_ln66_11_fu_554_p1 = trunc_ln302_10_fu_550_p1;

assign zext_ln66_12_fu_761_p1 = trunc_ln302_11_reg_1686;

assign zext_ln66_fu_519_p1 = control_bits_V_119;

endmodule //genChain_6
